export * from './cNAE.service';
import { CNAEService } from './cNAE.service';
export * from './especialidade.service';
import { EspecialidadeService } from './especialidade.service';
export * from './farmacia.service';
import { FarmaciaService } from './farmacia.service';
export * from './medicamento.service';
import { MedicamentoService } from './medicamento.service';
export * from './medico.service';
import { MedicoService } from './medico.service';
export * from './paciente.service';
import { PacienteService } from './paciente.service';
export * from './receita.service';
import { ReceitaService } from './receita.service';
export * from './substnciasControladasAnvisa.service';
import { SubstnciasControladasAnvisaService } from './substnciasControladasAnvisa.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [CNAEService, EspecialidadeService, FarmaciaService, MedicamentoService, MedicoService, PacienteService, ReceitaService, SubstnciasControladasAnvisaService, UserService];
