/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ApiResponse } from '../model/apiResponse';
import { Farmacia } from '../model/farmacia';
import { PaginationFarmacia } from '../model/paginationFarmacia';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FarmaciaService {

    protected basePath = 'http://localhost:8080/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Exclui o farmacia da base
     * 
     * @param farmaciaID ID do farmacia a ser consultado (CNPJ ou id objeto)
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFarmaciaById(farmaciaID: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFarmaciaById(farmaciaID: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFarmaciaById(farmaciaID: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFarmaciaById(farmaciaID: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (farmaciaID === null || farmaciaID === undefined) {
            throw new Error('Required parameter farmaciaID was null or undefined when calling deleteFarmaciaById.');
        }

        let headers = this.defaultHeaders;
        if (apiKey !== undefined && apiKey !== null) {
            headers = headers.set('api_key', String(apiKey));
        }

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/farmacia/${encodeURIComponent(String(farmaciaID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listagem de farmacias
     * Emite uma listagem de farmacias por busca de atributo, se nenhum parametro de busca for preenchido
     * @param cnpj busca farmacia pelo CNPJ
     * @param nome Nome ou parte do nome do farmacia
     * @param id busca farmacia pelo id do farmacia
     * @param email busca paciente pelo id do paciente
     * @param itemsPerPage Quantidade de registros por página
     * @param page Página (baseada em itemsPerPage)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFarmacia(cnpj?: string, nome?: string, id?: string, email?: string, itemsPerPage?: number, page?: number, observe?: 'body', reportProgress?: boolean): Observable<PaginationFarmacia>;
    public getFarmacia(cnpj?: string, nome?: string, id?: string, email?: string, itemsPerPage?: number, page?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PaginationFarmacia>>;
    public getFarmacia(cnpj?: string, nome?: string, id?: string, email?: string, itemsPerPage?: number, page?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PaginationFarmacia>>;
    public getFarmacia(cnpj?: string, nome?: string, id?: string, email?: string, itemsPerPage?: number, page?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cnpj !== undefined) {
            queryParameters = queryParameters.set('cnpj', <any>cnpj);
        }
        if (nome !== undefined) {
            queryParameters = queryParameters.set('nome', <any>nome);
        }
        if (id !== undefined) {
            queryParameters = queryParameters.set('id', <any>id);
        }
        if (email !== undefined) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (itemsPerPage !== undefined) {
            queryParameters = queryParameters.set('itemsPerPage', <any>itemsPerPage);
        }
        if (page !== undefined) {
            queryParameters = queryParameters.set('page', <any>page);
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<PaginationFarmacia>(`${this.basePath}/farmacia`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Encontra o farmacia pelo ID
     * Retorna um único farmacia
     * @param farmaciaID ID do farmacia a ser consultado (CNPJ ou id objeto)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFarmaciaById(farmaciaID: string, observe?: 'body', reportProgress?: boolean): Observable<Farmacia>;
    public getFarmaciaById(farmaciaID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Farmacia>>;
    public getFarmaciaById(farmaciaID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Farmacia>>;
    public getFarmaciaById(farmaciaID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (farmaciaID === null || farmaciaID === undefined) {
            throw new Error('Required parameter farmaciaID was null or undefined when calling getFarmaciaById.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Farmacia>(`${this.basePath}/farmacia/${encodeURIComponent(String(farmaciaID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Insere um novo farmacia na base
     * 
     * @param body O objeto JSON do farmacia a ser inserido
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFarmacia(body: Farmacia, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postFarmacia(body: Farmacia, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postFarmacia(body: Farmacia, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postFarmacia(body: Farmacia, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postFarmacia.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/farmacia`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Atualiza um farmacia na base
     * 
     * @param farmaciaID ID do farmacia a ser consultado (CNPJ ou id objeto)
     * @param body O objeto JSON do farmacia a ser atualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFarmaciaById(farmaciaID: string, body: Farmacia, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postFarmaciaById(farmaciaID: string, body: Farmacia, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postFarmaciaById(farmaciaID: string, body: Farmacia, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postFarmaciaById(farmaciaID: string, body: Farmacia, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (farmaciaID === null || farmaciaID === undefined) {
            throw new Error('Required parameter farmaciaID was null or undefined when calling postFarmaciaById.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postFarmaciaById.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/farmacia/${encodeURIComponent(String(farmaciaID))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * upload de foto do farmacia
     * 
     * @param farmaciaID ID do farmacia a ser consultado (CNPJ ou id objeto)
     * @param additionalMetadata Metadados Adicionais
     * @param file arquivo contendo a foto do farmacia
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postFarmaciaByIdUploadLogo(farmaciaID: string, additionalMetadata?: string, file?: Blob, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public postFarmaciaByIdUploadLogo(farmaciaID: string, additionalMetadata?: string, file?: Blob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public postFarmaciaByIdUploadLogo(farmaciaID: string, additionalMetadata?: string, file?: Blob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public postFarmaciaByIdUploadLogo(farmaciaID: string, additionalMetadata?: string, file?: Blob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (farmaciaID === null || farmaciaID === undefined) {
            throw new Error('Required parameter farmaciaID was null or undefined when calling postFarmaciaByIdUploadLogo.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (additionalMetadata !== undefined) {
            formParams = formParams.append('additionalMetadata', <any>additionalMetadata) || formParams;
        }
        if (file !== undefined) {
            formParams = formParams.append('file', <any>file) || formParams;
        }

        return this.httpClient.post<ApiResponse>(`${this.basePath}/farmacia/${encodeURIComponent(String(farmaciaID))}/uploadLogo`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Atualiza um farmacia da base
     * 
     * @param body O objeto JSON do farmacia a ser atualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFarmacia(body: Farmacia, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putFarmacia(body: Farmacia, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putFarmacia(body: Farmacia, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putFarmacia(body: Farmacia, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putFarmacia.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/farmacia`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
