/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SubstanciaAnvisa } from '../model/substanciaAnvisa';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SubstnciasControladasAnvisaService {

    protected basePath = 'http://localhost:8080/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Exclui o Substância Controladas Anvisa da base
     * 
     * @param substanciaAnvisaID ID do Substância Controladas Anvisa a ser consultado (CNPJ ou id objeto)
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSubstanciaAnvisaById(substanciaAnvisaID: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteSubstanciaAnvisaById(substanciaAnvisaID: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteSubstanciaAnvisaById(substanciaAnvisaID: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteSubstanciaAnvisaById(substanciaAnvisaID: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (substanciaAnvisaID === null || substanciaAnvisaID === undefined) {
            throw new Error('Required parameter substanciaAnvisaID was null or undefined when calling deleteSubstanciaAnvisaById.');
        }

        let headers = this.defaultHeaders;
        if (apiKey !== undefined && apiKey !== null) {
            headers = headers.set('api_key', String(apiKey));
        }

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/substanciaAnvisa/${encodeURIComponent(String(substanciaAnvisaID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listagem de Substâncias Controladas Anvisa
     * Emite uma listagem de Substâncias Controladas Anvisa (CBO) do profissional médico
     * @param descricao Nome ou parte da descricao do Substância Controladas Anvisa, slug ou e-mail
     * @param id busca Substância Controladas Anvisa pelo id do Substância Controladas Anvisa
     * @param itemsPerPage Quantidade de registros por página
     * @param page Página (baseada em itemsPerPage)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubstanciaAnvisa(descricao?: string, id?: string, itemsPerPage?: number, page?: number, observe?: 'body', reportProgress?: boolean): Observable<SubstanciaAnvisa>;
    public getSubstanciaAnvisa(descricao?: string, id?: string, itemsPerPage?: number, page?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubstanciaAnvisa>>;
    public getSubstanciaAnvisa(descricao?: string, id?: string, itemsPerPage?: number, page?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubstanciaAnvisa>>;
    public getSubstanciaAnvisa(descricao?: string, id?: string, itemsPerPage?: number, page?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (descricao !== undefined) {
            queryParameters = queryParameters.set('descricao', <any>descricao);
        }
        if (id !== undefined) {
            queryParameters = queryParameters.set('id', <any>id);
        }
        if (itemsPerPage !== undefined) {
            queryParameters = queryParameters.set('itemsPerPage', <any>itemsPerPage);
        }
        if (page !== undefined) {
            queryParameters = queryParameters.set('page', <any>page);
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<SubstanciaAnvisa>(`${this.basePath}/substanciaAnvisa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Encontra o Substância Controladas Anvisa pelo ID
     * Retorna um único Substância Controladas Anvisa
     * @param substanciaAnvisaID ID do Substância Controladas Anvisa a ser consultado (slug, cpf ou id objeto)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubstanciaAnvisaById(substanciaAnvisaID: string, observe?: 'body', reportProgress?: boolean): Observable<SubstanciaAnvisa>;
    public getSubstanciaAnvisaById(substanciaAnvisaID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubstanciaAnvisa>>;
    public getSubstanciaAnvisaById(substanciaAnvisaID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubstanciaAnvisa>>;
    public getSubstanciaAnvisaById(substanciaAnvisaID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (substanciaAnvisaID === null || substanciaAnvisaID === undefined) {
            throw new Error('Required parameter substanciaAnvisaID was null or undefined when calling getSubstanciaAnvisaById.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<SubstanciaAnvisa>(`${this.basePath}/substanciaAnvisa/${encodeURIComponent(String(substanciaAnvisaID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listagem de Substâncias Controladas Anvisa para combo
     * Emite uma listagem de Substâncias Controladas Anvisa (CBO) do profissional médico
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubstanciaAnvisaCombo(observe?: 'body', reportProgress?: boolean): Observable<Array<SubstanciaAnvisa>>;
    public getSubstanciaAnvisaCombo(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SubstanciaAnvisa>>>;
    public getSubstanciaAnvisaCombo(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SubstanciaAnvisa>>>;
    public getSubstanciaAnvisaCombo(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<SubstanciaAnvisa>>(`${this.basePath}/substanciaAnvisa/combo`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Insere ou atualiza uma nova Substância Controladas Anvisa na base
     * 
     * @param body O objeto JSON do Substância Controladas Anvisa a ser inserido
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postSubstanciaAnvisa(body: SubstanciaAnvisa, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postSubstanciaAnvisa.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/substanciaAnvisa`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Insere ou atualiza um Substância Controladas Anvisa na base
     * 
     * @param substanciaAnvisaID ID do Substância Controladas Anvisa a ser consultado (CNPJ ou id objeto)
     * @param body O objeto JSON do Substância Controladas Anvisa a ser atualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postSubstanciaAnvisaById(substanciaAnvisaID: string, body: SubstanciaAnvisa, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postSubstanciaAnvisaById(substanciaAnvisaID: string, body: SubstanciaAnvisa, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postSubstanciaAnvisaById(substanciaAnvisaID: string, body: SubstanciaAnvisa, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postSubstanciaAnvisaById(substanciaAnvisaID: string, body: SubstanciaAnvisa, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (substanciaAnvisaID === null || substanciaAnvisaID === undefined) {
            throw new Error('Required parameter substanciaAnvisaID was null or undefined when calling postSubstanciaAnvisaById.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postSubstanciaAnvisaById.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/substanciaAnvisa/${encodeURIComponent(String(substanciaAnvisaID))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Atualiza um Substância Controladas Anvisa da base
     * 
     * @param body O objeto JSON do Substância Controladas Anvisa a ser atualizado
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putSubstanciaAnvisa(body: SubstanciaAnvisa, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putSubstanciaAnvisa(body: SubstanciaAnvisa, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putSubstanciaAnvisa.');
        }

        let headers = this.defaultHeaders;

        // authentication (receitadigital_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/substanciaAnvisa`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
