/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UF } from './uF';


/**
 * Objeto que registra o tipo de documento de identidade ()
 */
export interface DocumentoIdentidade {
    /**
     * Código da carteira do CRF (Conselho Regional de Farmácia) do farmacêutico responsável pela farmácia
     */
    numero: number;
    /**
     * Identificação do emissor do documento
     */
    emissor?: DocumentoIdentidade.EmissorEnum;
    uf: UF;
    /**
     * data de validade do documento
     */
    validade?: string;
}
export namespace DocumentoIdentidade {
    export type EmissorEnum = 'ABNC' | 'CGPI/DUREX/DPF' | 'CGPI' | 'CGPMAF' | 'CNIG' | 'CNT' | 'COREN' | 'CRA' | 'CRAS' | 'CRB' | 'CRC' | 'CRE' | 'CREA' | 'CRECI' | 'CREFIT' | 'CRF' | 'CRM' | 'CRN' | 'CRO' | 'CRP' | 'CRPRE' | 'CRQ' | 'CRRC' | 'CRMV' | 'CSC' | 'CTPS' | 'DIC' | 'DIREX' | 'DPMAF' | 'DPT' | 'DST' | 'FGTS' | 'FIPE' | 'FLS' | 'GOVGO' | 'I CLA' | 'IFP' | 'IGP' | 'IICCECF/RO' | 'IIMG' | 'IML' | 'IPC' | 'IPF' | 'MAE' | 'MEX' | 'MMA' | 'OAB' | 'OMB' | 'PCMG' | 'PMMG' | 'POF ou DPF' | 'POM' | 'SDS' | 'SNJ' | 'SECC' | 'SEJUSP' | 'SES ou EST' | 'SESP' | 'SJS' | 'SJTC' | 'SJTS' | 'SPTC' | 'SSP' | '';
    export const EmissorEnum = {
        ABNC: 'ABNC' as EmissorEnum,
        CGPIDUREXDPF: 'CGPI/DUREX/DPF' as EmissorEnum,
        CGPI: 'CGPI' as EmissorEnum,
        CGPMAF: 'CGPMAF' as EmissorEnum,
        CNIG: 'CNIG' as EmissorEnum,
        CNT: 'CNT' as EmissorEnum,
        COREN: 'COREN' as EmissorEnum,
        CRA: 'CRA' as EmissorEnum,
        CRAS: 'CRAS' as EmissorEnum,
        CRB: 'CRB' as EmissorEnum,
        CRC: 'CRC' as EmissorEnum,
        CRE: 'CRE' as EmissorEnum,
        CREA: 'CREA' as EmissorEnum,
        CRECI: 'CRECI' as EmissorEnum,
        CREFIT: 'CREFIT' as EmissorEnum,
        CRF: 'CRF' as EmissorEnum,
        CRM: 'CRM' as EmissorEnum,
        CRN: 'CRN' as EmissorEnum,
        CRO: 'CRO' as EmissorEnum,
        CRP: 'CRP' as EmissorEnum,
        CRPRE: 'CRPRE' as EmissorEnum,
        CRQ: 'CRQ' as EmissorEnum,
        CRRC: 'CRRC' as EmissorEnum,
        CRMV: 'CRMV' as EmissorEnum,
        CSC: 'CSC' as EmissorEnum,
        CTPS: 'CTPS' as EmissorEnum,
        DIC: 'DIC' as EmissorEnum,
        DIREX: 'DIREX' as EmissorEnum,
        DPMAF: 'DPMAF' as EmissorEnum,
        DPT: 'DPT' as EmissorEnum,
        DST: 'DST' as EmissorEnum,
        FGTS: 'FGTS' as EmissorEnum,
        FIPE: 'FIPE' as EmissorEnum,
        FLS: 'FLS' as EmissorEnum,
        GOVGO: 'GOVGO' as EmissorEnum,
        ICLA: 'I CLA' as EmissorEnum,
        IFP: 'IFP' as EmissorEnum,
        IGP: 'IGP' as EmissorEnum,
        IICCECFRO: 'IICCECF/RO' as EmissorEnum,
        IIMG: 'IIMG' as EmissorEnum,
        IML: 'IML' as EmissorEnum,
        IPC: 'IPC' as EmissorEnum,
        IPF: 'IPF' as EmissorEnum,
        MAE: 'MAE' as EmissorEnum,
        MEX: 'MEX' as EmissorEnum,
        MMA: 'MMA' as EmissorEnum,
        OAB: 'OAB' as EmissorEnum,
        OMB: 'OMB' as EmissorEnum,
        PCMG: 'PCMG' as EmissorEnum,
        PMMG: 'PMMG' as EmissorEnum,
        POFOuDPF: 'POF ou DPF' as EmissorEnum,
        POM: 'POM' as EmissorEnum,
        SDS: 'SDS' as EmissorEnum,
        SNJ: 'SNJ' as EmissorEnum,
        SECC: 'SECC' as EmissorEnum,
        SEJUSP: 'SEJUSP' as EmissorEnum,
        SESOuEST: 'SES ou EST' as EmissorEnum,
        SESP: 'SESP' as EmissorEnum,
        SJS: 'SJS' as EmissorEnum,
        SJTC: 'SJTC' as EmissorEnum,
        SJTS: 'SJTS' as EmissorEnum,
        SPTC: 'SPTC' as EmissorEnum,
        SSP: 'SSP' as EmissorEnum,
        Empty: '' as EmissorEnum
    }
}
