/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MedicamentoPrecos {
    /**
     * Tipo de preco (fabrica ou consumidor associada ao custo 0%, 12%)
     */
    classe?: MedicamentoPrecos.ClasseEnum;
    /**
     * Valor de custo máximo a ser praticado
     */
    preco?: number;
}
export namespace MedicamentoPrecos {
    export type ClasseEnum = 'fabrica-custo' | 'fabrica-12' | 'fabrica-17' | 'fabrica-17-alc' | 'fabrica-17,5' | 'fabrica-17,5-alc' | 'fabrica-18' | 'fabrica-18-alc' | 'fabrica-20' | 'consumidor-custo' | 'consumidor-12' | 'consumidor-17' | 'consumidor-17-alc' | 'consumidor-17,5' | 'consumidor-17,5-alc' | 'consumidor-18' | 'consumidor-18-alc' | 'consumidor-20';
    export const ClasseEnum = {
        FabricaCusto: 'fabrica-custo' as ClasseEnum,
        Fabrica12: 'fabrica-12' as ClasseEnum,
        Fabrica17: 'fabrica-17' as ClasseEnum,
        Fabrica17Alc: 'fabrica-17-alc' as ClasseEnum,
        Fabrica175: 'fabrica-17,5' as ClasseEnum,
        Fabrica175Alc: 'fabrica-17,5-alc' as ClasseEnum,
        Fabrica18: 'fabrica-18' as ClasseEnum,
        Fabrica18Alc: 'fabrica-18-alc' as ClasseEnum,
        Fabrica20: 'fabrica-20' as ClasseEnum,
        ConsumidorCusto: 'consumidor-custo' as ClasseEnum,
        Consumidor12: 'consumidor-12' as ClasseEnum,
        Consumidor17: 'consumidor-17' as ClasseEnum,
        Consumidor17Alc: 'consumidor-17-alc' as ClasseEnum,
        Consumidor175: 'consumidor-17,5' as ClasseEnum,
        Consumidor175Alc: 'consumidor-17,5-alc' as ClasseEnum,
        Consumidor18: 'consumidor-18' as ClasseEnum,
        Consumidor18Alc: 'consumidor-18-alc' as ClasseEnum,
        Consumidor20: 'consumidor-20' as ClasseEnum
    }
}
