/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MedicamentoReceita {
    /**
     * Identifica qual a liste que 1 ou mais principios ativos que o remedio pertence
     */
    lista?: MedicamentoReceita.ListaEnum;
    /**
     * tipo extra de receita (notificação) que será demandada pelo sistema
     */
    notificacao?: MedicamentoReceita.NotificacaoEnum;
}
export namespace MedicamentoReceita {
    export type ListaEnum = 'A1' | 'A2' | 'A3' | 'B1' | 'B2' | 'C1' | 'C2' | 'C3' | 'C4' | 'C5' | 'D1' | 'D2' | 'E' | 'F1' | 'F2' | 'F3' | 'F4' | 'O' | 'N';
    export const ListaEnum = {
        A1: 'A1' as ListaEnum,
        A2: 'A2' as ListaEnum,
        A3: 'A3' as ListaEnum,
        B1: 'B1' as ListaEnum,
        B2: 'B2' as ListaEnum,
        C1: 'C1' as ListaEnum,
        C2: 'C2' as ListaEnum,
        C3: 'C3' as ListaEnum,
        C4: 'C4' as ListaEnum,
        C5: 'C5' as ListaEnum,
        D1: 'D1' as ListaEnum,
        D2: 'D2' as ListaEnum,
        E: 'E' as ListaEnum,
        F1: 'F1' as ListaEnum,
        F2: 'F2' as ListaEnum,
        F3: 'F3' as ListaEnum,
        F4: 'F4' as ListaEnum,
        O: 'O' as ListaEnum,
        N: 'N' as ListaEnum
    }
    export type NotificacaoEnum = 'A' | 'B' | 'DST' | 'RCE' | 'RERS' | 'N';
    export const NotificacaoEnum = {
        A: 'A' as NotificacaoEnum,
        B: 'B' as NotificacaoEnum,
        DST: 'DST' as NotificacaoEnum,
        RCE: 'RCE' as NotificacaoEnum,
        RERS: 'RERS' as NotificacaoEnum,
        N: 'N' as NotificacaoEnum
    }
}
