/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentoIdentidade } from './documentoIdentidade';


export interface PacienteRepresentantesLegais {
    /**
     * Código único do usuário do sistema
     */
    user?: string;
    /**
     * Código único do usuário do sistema
     */
    idPaciente?: string;
    /**
     * Código CPF do representante legal
     */
    cpf?: string;
    /**
     * Nome do médico
     */
    nome?: string;
    /**
     * Celular principal do responsável pela farmácia, será usado para validar ou assinar receitas
     */
    celular?: string;
    /**
     * e-mail principal do responsável pela farmácia, será usado para validações e informes
     */
    email?: string;
    identidade?: DocumentoIdentidade;
}
