/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentoIdentidade } from './documentoIdentidade';


export interface ReceitaMedico {
    /**
     * Código único do médico do sistema
     */
    id: string;
    /**
     * Código CPF do médico
     */
    cpf: string;
    crm?: DocumentoIdentidade;
    /**
     * Nome do médico
     */
    nome?: string;
}
