/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ReceitaMedicamentos {
    /**
     * id do objeto remédio na base medicamentos
     */
    id?: string;
    /**
     * Nome do Medicamento (redundância necessária para hash)
     */
    nome?: string;
    principiosAtivos?: Array<string>;
    /**
     * Descrevem a apresentação do produto
     */
    apresentacao?: string;
    /**
     * Quantidade de medicamentos, na unidade da apresentação, foi prescrita
     */
    quantidade?: number;
    /**
     * Qual o periodo de uso do medicamento
     */
    frequencia?: string;
    /**
     * Indicação de uso do medicamento
     */
    posologia?: string;
}
