/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubstanciaAnvisaClassificacao } from './substanciaAnvisaClassificacao';


export interface SubstanciaAnvisa {
    /**
     * código global único da medicamento, usado no
     */
    id?: string;
    /**
     * nome oficial da substância
     */
    substancia?: string;
    /**
     * nome popular ou mais conhecido da substância
     */
    nomePopular?: string;
    /**
     * Observações e outras anotações
     */
    observacoes?: string;
    classificacao?: SubstanciaAnvisaClassificacao;
}
