/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * classificacao anvisa da substância
 */
export interface SubstanciaAnvisaClassificacao {
    /**
     * Tipo ou lista de classificação de substâncias
     */
    tipo?: string;
    /**
     * descrição do tipo ou lista que a substância pertence
     */
    descricao?: SubstanciaAnvisaClassificacao.DescricaoEnum;
    /**
     * tipo ou subtipo de receita que a substância demanda
     */
    receita?: SubstanciaAnvisaClassificacao.ReceitaEnum;
}
export namespace SubstanciaAnvisaClassificacao {
    export type DescricaoEnum = 'A1' | 'A2' | 'A3' | 'B1' | 'B2' | 'C1' | 'C2' | 'C3' | 'C4' | 'C5' | 'D1' | 'D2' | 'E' | 'F1' | 'F2' | 'F3' | 'F4' | 'O' | 'N';
    export const DescricaoEnum = {
        A1: 'A1' as DescricaoEnum,
        A2: 'A2' as DescricaoEnum,
        A3: 'A3' as DescricaoEnum,
        B1: 'B1' as DescricaoEnum,
        B2: 'B2' as DescricaoEnum,
        C1: 'C1' as DescricaoEnum,
        C2: 'C2' as DescricaoEnum,
        C3: 'C3' as DescricaoEnum,
        C4: 'C4' as DescricaoEnum,
        C5: 'C5' as DescricaoEnum,
        D1: 'D1' as DescricaoEnum,
        D2: 'D2' as DescricaoEnum,
        E: 'E' as DescricaoEnum,
        F1: 'F1' as DescricaoEnum,
        F2: 'F2' as DescricaoEnum,
        F3: 'F3' as DescricaoEnum,
        F4: 'F4' as DescricaoEnum,
        O: 'O' as DescricaoEnum,
        N: 'N' as DescricaoEnum
    }
    export type ReceitaEnum = 'A' | 'B' | 'DST' | 'RCE' | 'RERS' | 'N';
    export const ReceitaEnum = {
        A: 'A' as ReceitaEnum,
        B: 'B' as ReceitaEnum,
        DST: 'DST' as ReceitaEnum,
        RCE: 'RCE' as ReceitaEnum,
        RERS: 'RERS' as ReceitaEnum,
        N: 'N' as ReceitaEnum
    }
}
