/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Estado do endereço, favor enviar dado de acordo com a tabela do IBGE
 */
export type UF = 'AC' | 'AL' | 'AM' | 'AP' | 'BA' | 'CE' | 'DF' | 'ES' | 'GO' | 'MA' | 'MT' | 'MS' | 'MG' | 'PA' | 'PB' | 'PR' | 'PE' | 'PI' | 'RJ' | 'RN' | 'RO' | 'RS' | 'RR' | 'SC' | 'SE' | 'SP' | 'TO' | '';

export const UF = {
    AC: 'AC' as UF,
    AL: 'AL' as UF,
    AM: 'AM' as UF,
    AP: 'AP' as UF,
    BA: 'BA' as UF,
    CE: 'CE' as UF,
    DF: 'DF' as UF,
    ES: 'ES' as UF,
    GO: 'GO' as UF,
    MA: 'MA' as UF,
    MT: 'MT' as UF,
    MS: 'MS' as UF,
    MG: 'MG' as UF,
    PA: 'PA' as UF,
    PB: 'PB' as UF,
    PR: 'PR' as UF,
    PE: 'PE' as UF,
    PI: 'PI' as UF,
    RJ: 'RJ' as UF,
    RN: 'RN' as UF,
    RO: 'RO' as UF,
    RS: 'RS' as UF,
    RR: 'RR' as UF,
    SC: 'SC' as UF,
    SE: 'SE' as UF,
    SP: 'SP' as UF,
    TO: 'TO' as UF,
    Empty: '' as UF
}
