/**
 * Receita Digital
 * Definição da API da Receita Digital 
 *
 * OpenAPI spec version: 1.0.6
 * Contact: fran.fig@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserLinksFarmacia {
    /**
     * Código único do atendente/farmaceutico no sistema
     */
    id?: string;
    /**
     * função do usuário nessa farmácia
     */
    funcao?: UserLinksFarmacia.FuncaoEnum;
}
export namespace UserLinksFarmacia {
    export type FuncaoEnum = 'atendente' | 'farmaceutico' | 'responsavel' | 'administrativo';
    export const FuncaoEnum = {
        Atendente: 'atendente' as FuncaoEnum,
        Farmaceutico: 'farmaceutico' as FuncaoEnum,
        Responsavel: 'responsavel' as FuncaoEnum,
        Administrativo: 'administrativo' as FuncaoEnum
    }
}
